source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'TableviewPaginator_Example' do
  pod 'TableviewPaginator', :path => '../'
  pod 'Alamofire', '~> 4.7.3', :inhibit_warnings => true
  pod 'SDWebImage', '~> 4.4.2', :inhibit_warnings => true

  target 'TableviewPaginator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4',   :inhibit_warnings => true
  end
end
