use_frameworks!

target 'TableviewPaginator_Example' do
  pod 'TableviewPaginator', :path => '../'

  target 'TableviewPaginator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
